### PR TITLE
Opal prd service

### PR DESCRIPTION
**Pull request by r4f4**
Remove unused socket file and add conditions to the service file so that systemd doesn't try to run it on unsupported systems.

---

This change is [Reviewable](https://reviewable.io/reviews/open-power/skiboot/40)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Hi!

We normally do patches via the mailing list (see https://lists.ozlabs.org/listinfo/skiboot ), although I'm also happy to pull via github.

However, we do need things to conform to the Developer Certificate of Origin (http://developercertificate.org/ ) - i.e. use "git commit -s" to get the "Signed-off-by" tag in your commit message.

Are you able to add Signed-off-by and either resubmit here or post patches to the list?

**Comment by r4f4** [comment]
I've sent the patches to the mailing list. The email is probably awaiting moderator's approval.

**Comment by stewart-ibm** [comment]
"Rafael F." <notifications@github.com> writes:
> I've sent the patches to the mailing list. The email is probably
> awaiting moderator's approval.

Yep, saw it this morning. I'll look at them today, thanks!


-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
Closing this PR as was dealt with via mailing list.

**Pull request closed without merging**
