### PR TITLE
[Stable branch] skiboot v6.0.16

### PR DESCRIPTION
**Pull request by hegdevasant**

### CODE REVIEW

**Comment by jk-ozlabs** [comment]
@debmc has mentioned that the PR at https://github.com/open-power/skiboot/pull/216 is the second part of the p9dsu fix. Deb - is it worthwhile only having the first part of this change in this proposed 6.0.16 release? Or do we need both here for this to be a proper fix?

In the latter case, we'll need to have that merged to stable and then included in this change set.

**Comment by jk-ozlabs** [comment]
(and has the combination of both patches been tested?)

**Comment by debmc** [comment]
>  is it worthwhile only having the first part of this change in this proposed 6.0.16 release

Yes, the first part of the fix addresses the functionality of getting the subordinate buses set.

The second patch addresses defining the slots for the slot labeling to be created and addresses the subordinate bus settings.

The first patch has been tested as well as with the second patch on top of the first patch.

The delivery needed for the Boston LA service pack I believe is delayed, so the urgency here may be relieved, but I'm not sure on that.  It would be best to make sure the first patch gets delivered asap, second patch can come at anytime.

**Comment by youhour** [comment]
Look like Ravi is pushing really hard to get Boston op910 and op920 release next week.  So, please get this merge as soon as you can.

Let @ravimed1 knows if you have any question.

**Comment by hegdevasant** [comment]
Stewart has merged along with few other patches. Lets close this PR.

-Vasant

**Comment by youhour** [comment]
Hmm.  I do not see this change in ibm-op-release/skiboot in 6.0.x branch.  Please check just in case I looked at the wrong place.  Send me a link if you see it exists.

**Comment by hegdevasant** [comment]
@youhour waiting for upstream op-build to accept the changes [1]. Once it gets accepted in upstream, we will send PR to ibm-op-release.

[1] https://github.com/open-power/op-build/pull/2607

-Vasant

**Pull request closed without merging**
