### PR TITLE
Updated hbrt interfaces to match latest in Hostboot

### PR DESCRIPTION
**Pull request by dcrowell77**
Matches with Hostboot commit:
  c068f50829ec46e4e5b056064dcbe9d786d549a4

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by stewart-ibm** [comment]
A couple of problems:
1) It doesn't build (see https://travis-ci.org/open-power/skiboot/builds/49196573 )
2) Needs to have Signed-off-by line
3) please email patch to skiboot@lists.ozlabs.org

**Comment by williamspatrick** [comment]
libc/include/time.h seems to not include clockid_t, which is POSIX.

In Hostboot we have a typedef from 'struct timespec' to 'timespec_t' that also appears missing in time.h.  I don't think that typedef is POSIX so we should probably remove it in the case of the interface file.

**Comment by dcrowell77** [comment]
I thought we had discussed this interface and Ben said it was okay, guess 
not...

So we want 'timespec_t' to become 'struct timespec'?

--
Dan Crowell - PFD Cec Enablement
IBM Rochester: t/l 553-2987
dcrowell@us.ibm.com

**Comment by dcrowell77** [comment]
1) How do I compile skiboot locally?  I cloned it locally and typed make, 
it didn't even start to do anything.  I didn't see anything in the README.

2) Rather than have me poke around the Linux patch guidelines for a couple 
hours, can you explain this to me?  What is the format?

3) So I can't just submit the pull request directly in github?

--
Dan Crowell - PFD Cec Enablement
IBM Rochester: t/l 553-2987
dcrowell@us.ibm.com

**Comment by williamspatrick** [comment]
#2 - 'git commit --signoff' will automatically add it.  Can be paired with '--amend' in this case.

**Comment by stewart-ibm** [comment]
Dan <notifications@github.com> writes:
> 1) How do I compile skiboot locally?  I cloned it locally and typed make, 
> it didn't even start to do anything.  I didn't see anything in the
> README.

What i do is:

LIB_DIR=~/mambo/lib/ MAMBO_PATH=/home/stewart/mambo/ \
MAMBO_BINARY=/bin/systemsim-pegasus \
PATH=/opt/cross/gcc-4.8.0-nolibc/powerpc64-linux/bin/:$PATH \
make

LIB_DIR=~/mambo/lib/ MAMBO_PATH=/home/stewart/mambo/ \
MAMBO_BINARY=/bin/systemsim-pegasus \
PATH=/opt/cross/gcc-4.8.0-nolibc/powerpc64-linux/bin/:$PATH \
make -j12 check

Which does build and unit tests. If on modern Ubuntu and have the cross
compilers installed it should "just work"


> 2) Rather than have me poke around the Linux patch guidelines for a couple 
> hours, can you explain this to me?  What is the format?

"git commit -s" will do it for you.

It addes something like this to your commit message:
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

and then, people can reply to list with "acked-by, reviewed-by" etc and
it gets gather up by patchwork so when I pull it in you can see the full
audit trail of how code got into the tree.

> 3) So I can't just submit the pull request directly in github?

We prefer to go via the list so we have a better way to discuss and
track. That way, patches go into patchwork, which makes it easier for me
to track discussion, acks etc.

**Comment by williamspatrick** [comment]
‎Dan, you will need to use the cross compiler from an op-build. Take a look at skiboot.mk under buildroot for the right make incantation.                                                                                                                                                                                                                                          From: Stewart SmithSent: Monday, February 2, 2015 5:29 PMTo: open-power/skibootReply To: open-power/skibootCc: Patrick WilliamsSubject: Re: [skiboot] Updated hbrt interfaces to match latest in Hostboot (#8)Dan <notifications@github.com> writes:
> 1) How do I compile skiboot locally?  I cloned it locally and typed make, 
> it didn't even start to do anything.  I didn't see anything in the
> README.

What i do is:

LIB_DIR=~/mambo/lib/ MAMBO_PATH=/home/stewart/mambo/ \
MAMBO_BINARY=/bin/systemsim-pegasus \
PATH=/opt/cross/gcc-4.8.0-nolibc/powerpc64-linux/bin/:$PATH \
make

LIB_DIR=~/mambo/lib/ MAMBO_PATH=/home/stewart/mambo/ \
MAMBO_BINARY=/bin/systemsim-pegasus \
PATH=/opt/cross/gcc-4.8.0-nolibc/powerpc64-linux/bin/:$PATH \
make -j12 check

Which does build and unit tests. If on modern Ubuntu and have the cross
compilers installed it should "just work"


> 2) Rather than have me poke around the Linux patch guidelines for a couple 
> hours, can you explain this to me?  What is the format?

"git commit -s" will do it for you.

It addes something like this to your commit message:
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

and then, people can reply to list with "acked-by, reviewed-by" etc and
it gets gather up by patchwork so when I pull it in you can see the full
audit trail of how code got into the tree.

> 3) So I can't just submit the pull request directly in github?

We prefer to go via the list so we have a better way to discuss and
track. That way, patches go into patchwork, which makes it easier for me
to track discussion, acks etc.

—Reply to this email directly or view it on GitHub.

**Comment by dcrowell77** [comment]
I fixed the timespec issue but I can't find anything like clockid_t 
anywhere.  I see some of the skiboot code using CLOCK_MONOTONIC but I 
don't see it defined anywhere in the code base so it must be coming from 
some system include?

external/pflash/progress.c:     clock_gettime(CLOCK_MONOTONIC, 
&progress_start);}
external/pflash/progress.c:     clock_gettime(CLOCK_MONOTONIC, &now);

Where is skiboot getting these constants from?
--
Dan Crowell - PFD Cec Enablement
IBM Rochester: t/l 553-2987
dcrowell@us.ibm.com

**Comment by williamspatrick** [comment]
Those are external tools (pflash) which use standard linux headers.
Doesn't sound like skiboot actually implements the POSIX clock_gettime
function yet so they wouldn't have those enums.

**Comment by stewart-ibm** [comment]
Patrick Williams <notifications@github.com> writes:
> Those are external tools (pflash) which use standard linux headers.
> Doesn't sound like skiboot actually implements the POSIX clock_gettime
> function yet so they wouldn't have those enums.

correct.

**Comment by ozbenh** [comment]
On Mon, 2015-02-02 at 14:18 -0800, Dan wrote:
> I thought we had discussed this interface and Ben said it was okay,
> guess 
> not... 
> 
> So we want 'timespec_t' to become 'struct timespec'? 

I'm happy with implementing more posix-ish bits in skiboot

I prefer struct timespec to timespec_t (never been fan of typedef's
myself but that's a matter of taste).

Ben.

**Comment by stewart-ibm** [comment]
This has sat idle without being updated for nearly a year, closing.

**Pull request closed without merging**
