### PR TITLE
Update opal-flash-110-111-112.rst

### PR DESCRIPTION
**Pull request by jnider**
correct typo: much -> must

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/skiboot/85)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Thanks so much for your patch and pull request!

One small thing I need before I can merge it though is a Signed-off-by line, as per Developer Certificate of Origin (see https://github.com/open-power/skiboot/blob/master/CONTRIBUTING.md#developer-certificate-of-origin ). This keeps a good solid audit log of where code comes from and through who (and we use it for all the same reasons as the Linux Kernel does).

A simple way to do it is "git commit --amend -s".

**Comment by jnider** [comment]
I signed off the patch - do I need to create a new pull request?

**Comment by stewart-ibm** [comment]
Joel Nider <notifications@github.com> writes:
> I signed off the patch - do I need to create a new pull request?

No, it's fine, I can take it from there.

Thanks!

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
I went to merge this, but I think you forgot to "git push -f" to the branch as the commit there doesn't have the 'Signed-off-by' tag in it.

**Pull request closed without merging**
