### PR TITLE
5.10 cherry-picked fixes

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by hegdevasant** [comment]
Looks ok to me. But I'm not sure whether its still worth to backport patches to v5.10.x.

May be you should move to v6.[02].x branches.

Lets wait for @stewart-ibm to comment on this.


-Vasant

**Comment by stewart-ibm** [comment]
Yeah, we're not doing much on 5.10.x, but if someone wants patches, I don't really have a problem in merging and tagging a release.

**Comment by hegdevasant** [comment]
@hramrach

Can you please justify why you want these changes in 5.10.x stable branch ? 

-Vasant

**Comment by hramrach** [comment]
To be able to build 5.10 with current toolchain. We have it in a 'stable' distribution so will build it for a while still. I don't see any problem with carrying the patches locally either.

**Comment by oohal** [comment]
Merged #232 which has these commits + release notes, so closing this one.

**Pull request closed without merging**
