### PR TITLE
Add initial Talos II support to skiboot

### PR DESCRIPTION
**Pull request by madscientist159**
This series adds intiial support for Talos II to skiboot.  It includes:
* Descriptor copy / rename
* LPC IPL status patches
* MTD fixups

### CODE REVIEW

**Comment by mikey** [comment]
Thanks! Could you send these to the skiboot mailing list? Generally we do reviews there rather than github PRs. Should be a simply: 
``` git send-email --to skiboot@lists.ozlabs.org origin/master..master ```

**Comment by mikey** [comment]
BTW can you add a "why" to your commit messages. For example, the last patch marks things as read only, but doesn't mention why you are doing that. 
What is happening can reconstructed later, but the why can't, so it's best to put this in the commit message.

**Comment by madscientist159** [comment]
@mikey Uploaded, https://lists.ozlabs.org/pipermail/skiboot/2019-April/014094.html

**Comment by madscientist159** [comment]
Merged in master after ML review.

**Pull request closed without merging**
